version: '3.8'

services:
    db:
        image: mariadb:11.0.2
        restart: on-failure
        networks:
            backend:
        environment:
            MARIADB_DATABASE: renewableEnergy
            MARIADB_USER: user
            MARIADB_PASSWORD: password
            MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: yes

    backend:
        build:
            dockerfile: ./jar.Dockerfile
        ports:
            - '127.0.0.1:8080:8080'
        networks:
            backend:
        depends_on:
            - db
        restart: on-failure

    frontend:
        build:
            context: integracja_front
        ports:
            - '127.0.0.1:4321:4321'
        networks:
            backend:
        depends_on:
            - backend
        restart: on-failure

networks:
    backend:
